name = "admin-monitor"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "ADMIN_MONITOR_CACHE"
id = "8e18ff5b5b894dbf91ef20294716512d"

[[d1_databases]]
binding = "DB"
database_name = "admin_monitor_db"
database_id = "99ec69d4-d39d-4b07-859f-b6bc17f753f9"

[vars]
ENVIRONMENT = "production"

# Cron Trigger - ตรวจสอบออเดอร์ทุก 30 นาที
[triggers]
crons = ["*/30 * * * *"]
